version: "3.8"
services:
    api-server:
        image: api-server
        ports:
            - "3100:3100"
        networks:
            - "api"
        depends_on: 
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks: 
            - "api"
        volumes: 
            - "mongo-data:/data/db"
networks: 
    api:
        driver: bridge
volumes:
    mongo-data:
        driver: local